applications:
  - type: http_s
    host: 0.0.0.0
    port: 80
    origin_host: 127.0.0.1
    origin_port: 8000
    certificate: /path/cert.pem
    private_key: /path/key.pem
    vulnerabilities:
      - CVE-2016-10073
