[tool.poetry]
name = "firehole"
version = "0.1.0"
description = ""
authors = [
    "Jiří Rája <raja@ics.muni.cz>",
    "Daniel Volf <248688@mail.muni.cz>",
]
maintainers = [
    "Jiří Rája <raja@ics.muni.cz>",
    "Daniel Volf <248688@mail.muni.cz>",
]
readme = "README.md"
packages = [{include = "firehole", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
